name: TF Pipeline

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  static-analysis:
    uses: ./.github/workflows/static-analysis.yml
    with:
      python-version: '3.12'

  validate:
    permissions:
      id-token: write
      contents: read
    needs: static-analysis
    uses: ./.github/workflows/terraform-validate.yml

  # plan:
  #   needs: validate
  #   uses: ./.github/workflows/terraform-plan.yml

  # apply:
  #   needs: plan
  #   if: github.event_name == 'push'
  #   uses: ./.github/workflows/terraform-apply.yml

  # destroy:
  #   if: github.event_name == 'workflow_dispatch'
  #   uses: ./.github/workflows/terraform-destroy.yml
